config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get 'main/index'

  resources :books do
    member do
      get :delete
    end
  end

  # get 'books/index'
  # get 'books/new'
  # get 'books/edit'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @page = params[:page].to_i
    @books = Book.order(:id)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    
  end

  def create
    @book = Book.new(book_params)
    if @book.save 
      flash[:notice] = "Book was successfully added."
      redirect_to books_path
    else
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice] = "Book was successfully updated."
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
    flash[:notice] = "Book was successfully deleted."
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :price, :published_date)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/books/_form.html.erb
<table summary="Book form fields">
    <tr>
    <th>Name</th>
    <td><%= f.text_field(:title) %></td>
    </tr>
    <tr>
    <th>Author</th>
    <td><%= f.text_field(:author) %></td>
    </tr>
    <tr>
    <th>Price</th>
    <td><%= f.text_field(:price) %></td>
    </tr>
    <tr>
    <th>Published Date</th>
    <td><%= f.date_field(:published_date) %></td>
    </tr>
</table>

app/views/books/delete.html.erb
<%= link_to("Back to Homepage", books_path, class: 'back-link') %>

<div class="book delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, method: 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("Back to Homepage", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Edit Book</h2>

  <%= form_for(@book) do |f| %>
    <% # url: books_path(@book), method: 'patch' %>

    <%= render(partial: 'form', locals:{f: f})%> 
    <%# local, partial %>

    <div class="form-buttons">
      <%= f.submit("Edit book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<div class="books index">
    <% if flash[:notice].present? %>
        <div id="myModal" class="modal">
            <div class="modal-content">
            <span class="close">&times;</span>
            <p><%= flash[:notice] %></p>
            </div>
        </div>
        <script>
            // Get the modal
            var modal = document.getElementById("myModal");

            // Get the <span> element that closes the modal
            var span = document.getElementsByClassName("close")[0];

            // When the user clicks on <span> (x), close the modal
            span.onclick = function() {
            modal.style.display = "none";
            };

            // When the user clicks anywhere outside of the modal, close it
            window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
            };

            // Display the modal
            modal.style.display = "block";
        </script>
    <% end %>


    <h2> My Books </h2>

    <%= link_to("Add New book", new_book_path, class: 'action new')%>

    <table class="listing" summery = "book list" style="width:100%">
        <tr class="header">
            <th>Title</th>
            <th>Author</th>
            <th>Price</th>
            <th>Published Date</th>
        </tr>
        <% @books.each do |book| %>
        <tr>
            <th><%= book.title %></th>
            <th><%= book.author %></th>
            <th><%= book.price %></th>
            <th><%= book.published_date %></th>
            <td class="action">
                <%= link_to("Show", book_path(book), class: 'action show')%>
                <%= link_to("Edit", edit_book_path(book), class: 'action edit')%>
                <%= link_to("Delete", delete_book_path(book), class: 'action delete')%>
            </td>
        </tr>
        <%end%>
    </table>
</div>

app/views/books/new.html.erb
<%= link_to("Back to Homepage", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Add Book</h2>

  <%= form_for(@book) do |f| %>

   <%= render(partial: 'form', locals:{f: f})%> 

    <div class="form-buttons">
      <%= f.submit("Add Book") %>
    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to("Back to Homepage", books_path, class: 'back-link') %>

<div class="books show">
  <h2>Show Book</h2>

  <div class="actions">
    <%= link_to('Edit', edit_book_path(@book)) %>
    <%= link_to('Delete',  delete_book_path(@book)) %>
  </div>

  <table summary="book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td><%= @book.published_date %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Week1LabLilyttt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Book Collection</h1>
<p>This is an application for managing your books!</p>

<%= link_to('Books', books_path(page:1)) %> <br>